name: CI - Go Text to Speech

on:
  push:
    branches: ["main"]
    tags:
      - "v*"
  pull_request:
    branches: ["main"]

permissions:
  contents: write
  packages: write

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Show Git ref
        run: |
          echo "Running on ref: $GITHUB_REF"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.4"
          cache: true

      - name: Install golangci-lint (from source, Go 1.25)
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run golangci-lint
        run: golangci-lint run --timeout=5m

      - name: Install coverage dependencies
        run: sudo apt install -y bc

      - name: Install OS dependencies
        run: |
          sudo apt update
          sudo apt install -y espeak

      - name: Run tests with coverage
        run: |
          go test -coverprofile=coverage.out ./...
          COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
          echo "Total coverage: $COVERAGE%"
          if (( $(echo "$COVERAGE < 60" | bc -l) )); then
          echo "Coverage below threshold"
          exit 1
          fi

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.out

      - name: Login to Github Container Registry
        if: startsWith(github.ref, 'refs/tagsclear/')
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker image
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          IMAGE=ghcr.io/$REPO:$VERSION

          echo "Build $IMAGE"
          docker build -t $IMAGE .

          echo "Pushing $IMAGE"
          docker push $IMAGE

      - name: Create Github Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
